### ISSUE TITLE
StreetSplitter fails on missing space between street and number

### ISSUE THREAD

**Issue by HenKun** [netresearch/dhl-shipping-m2#21]
Although `Dhl\ShippingCore\Model\Util\StreetSplitter` has a massively complex regex, it fails on the simple case where there is no space between street name and house number.

E.g. `Musterstraße12` as street name leads to a not detected house number, see the following screenshot.

![image](https://user-images.githubusercontent.com/18382633/104160845-184fb500-53f2-11eb-88b9-718b9cec30d1.png)

Labels cannot be created due to this issue and the address needs to be corrected manually.

We now solved it on our end with a custom plugin that matches this case, but it would be better if DHL Core module itself solves the issue.

**Comment by mam08ixo** [comment]
The street splitter is able to extract street name and number from valid addresses. Your input is not a valid address format.

Address form validation is a completely different thing and not the responsibility of the shipping module.
If you need assistance with address auto-completion and verification, I suggest having a look at the [Deutsche Post modules](https://marketplace.magento.com/partner/Deutsche+Post#partner.products.info) bundled with the extension since v1.3.0.

**Comment by ngolatka** [comment]
@HenKun I'd also like to point out that this case is not as simple as it might look. Please see [this Github issue](https://github.com/netresearch/dhl-module-shipping-m2/issues/20) for a (very lengthy) discussion on the reasons.

There are in fact street names with numbers in them, like "M1" and many more in Mannheim, Germany.

**Comment by HenKun** [comment]
@ngolatka Thanks for the link, interesting considerations. I see the reasoning. We solved it on our site 'cause we more often have malformatted input than weird addresses from Mannheim. But it cannot be generalized, of course, so making a custom solution for our case is pretty fine.
