### ISSUE TITLE
Which module to enable?

### ISSUE THREAD

**Issue by azngeek** [netresearch/dhl-shipping-m2#32]
What is the right module to enable? It seems like that there are these modules:

        "deutschepost/module-autocomplete-m2": "~1.1.1",
        "deutschepost/module-addressfactory-m2": "~1.1.2",
        "deutschepost/module-internetmarke": "~2.0.0",
        "dhl/module-carrier-paket": "~2.0.0",
        "dhl/module-carrier-paket-returns": "~2.0.0",
        "netresearch/module-shipping-ui": "~2.0.1"

According to the installation instructions there seems to be something missing.

![image](https://user-images.githubusercontent.com/213429/115893224-3c427e00-a458-11eb-8655-db00e6df76cf.png)

**Comment by mam08ixo** [comment]
As far as I can tell, `setup:upgrade` enables all modules. Not sure what you mean by "something missing".

However, some modules are indeed optional depending on your needs. If you do not intend to use the Deutsche Post services, then the `deutschepost/*` modules can safely be uninstalled.

**Comment by azngeek** [comment]
No not really. You need to enable a module for example using ```bin/magento module:enable <module_name>```. It is not clear from the documentation which one to enable.

**Comment by mam08ixo** [comment]
I can only repeat myself: `setup:upgrade` **does** enable all installed modules. No need to enable all of them individually.

Having all installed modules enabled is the standard use case (otherwise, why would we ship them?). If you know what you are doing, then it is still fine to disable or uninstall the modules that you are not going to use.
