### ISSUE TITLE
Mapbox API is deprecated - HTTP 410 error

### ISSUE THREAD

**Issue by dwirt** [netresearch/dhl-shipping-m2#4]
When trying to use the Location Finder with a new Mapbox API Token the Map isn't loaded and you can see in the Browser Console that the API Request is returning a 410 Error.
When calling the API Request separately in a new Tab you get the following Message:

{"message":"Classic styles are no longer supported; see https://blog.mapbox.com/deprecating-studio-classic-styles-d8892ac38cb4 for more information"}

The Link explains that no more new requests will be accepted:
> Then on June 1st, we will no longer support requests to our Legacy Maps and Legacy Static Images APIs from new applications and websites.

It also explains how to transition to the new Style.

This currently makes the Location Finder unusable in any new Shop.

**Comment by ngolatka** [comment]
Thanks for reporting this, @dwirt. Much appreciated!

This issue has been fixed in [version 1.1.0](https://github.com/netresearch/dhl-shipping-m2/tree/1.1.0), released just yesterday. The actual code changes are in these packages:
* https://github.com/netresearch/dhl-module-ui/tree/1.1.0
* https://github.com/netresearch/dhl-module-carrier-paket/tree/1.1.0

Please confirm it works for you and then close this issue.

**Comment by dwirt** [comment]
version 1.1.0 did indeed fix the issue, thank you very much
