### ISSUE TITLE
mass-action shipping label generation not working

### ISSUE THREAD

**Issue by grilovolom** [netresearch/dhl-shipping-m2#9]
Hello,

I am currently working on migrating to your new magento shipping extension (dhl-shipping-m2) from the deprecated one (dhl-module-shipping-m2 or DHL Versenden). The following documentation was a great help to me: https://github.com/netresearch/dhl-module-carrier-paket/wiki/Documentation-English. After setting the extension up and configuring the settings for shipping label print-outs, I tried generating labels via mass-action. For this I used the newly present option in the orders menu: "DHL Shipping". However, despite the manual label generation working perfectly fine, using the mass-action returns "Order cannot be shipped with DHL". This was only tried with orders made using the new extension. The old option "Create shipping labels" still works for its respective orders. 
It might also be important to mention, that the DHL Label Status always shows "Not Available" for the new orders.

I hope you can help me fix this problem.

**Comment by ngolatka** [comment]
Hello @grilovolom You've also contacted us via our tech support mail address. I'm going to reply to you there (ticket DHLSUP-1057193).

After your issue has been resolved, I'm going to post a summary here.

**Comment by ngolatka** [comment]
An intermediate status update, in case other people are watching:

I was not able to duplicate this problem on my test system, using Magento 2.3.5 and extension version 1.2.0. Everything worked just fine. Will post an update here when @grilovolom 's problem has been resolved.

**Comment by ngolatka** [comment]
The problem seems to boil down to this: the [mass-actions](https://github.com/netresearch/dhl-module-carrier-paket/wiki/Documentation-English#how-to-batch-process-shipments-mass-action) of the two DHL Shipping modules ([legacy 0.11.x](https://github.com/netresearch/dhl-module-shipping-m2) and [current module 1.x](https://github.com/netresearch/dhl-shipping-m2)) interfere with each other. However, it is still possible to manually create DHL labels, i.e. using the shipping popup dialog of the legacy module.

Since this is only relevant for a short time (during migrating from the legacy module to the current module), the suggested solution is:
1. Process the old orders which need to be handled by the legacy module, using the shipping popup dialog
2. When done, remove the legacy module completely ([instructions are here](https://github.com/netresearch/dhl-module-shipping-m2/blob/master/README.md#uninstallation)

**Comment by ngolatka** [comment]
Closing this, since there have been no further questions.

Not happy? Feel free to reopen this issue.
